export const CREATE_LESSON = "CREATE_LESSON";
export const FIND_LESSONS_FOR_MODULE = "FIND_LESSONS_FOR_MODULE";
export const FIND_LESSONS = "FIND_LESSON";
export const UPDATE_LESSON = "UPDATE_LESSON";
export const DELETE_LESSON = "DELETE_LESSON";