export const CREATE_MODULE = "CREATE_MODULE";
export const FIND_MODULES_FOR_COURSE = "FIND_MODULES_FOR_COURSE";
export const FIND_MODULE = "FIND_MODULE";
export const UPDATE_MODULE = "UPDATE_MODULE";
export const DELETE_MODULE = "DELETE_MODULE";